name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  actions: read
  contents: read

jobs:
  pr-title-check:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check PR title for Conventional Commits format
        uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          filter: tree:0
          fetch-depth: 0

      # Run this command as early as possible, before dependencies are installed
      - name: Task distribution via Nx Cloud
        run: npx nx start-ci-run --distribute-on="3 linux-medium-js" --stop-agents-after="build"

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install Deps
        run: npm ci --legacy-peer-deps

      # Prepend any command with "nx-cloud record --" to record its logs to Nx Cloud
      # - run: npx nx-cloud record -- echo Hello World
      - name: Lint
        run: npx nx affected -t lint

      - name: Test
        run: npx nx affected -t test

      - name: Build
        run: npx nx affected -t build

      - name: Nx fix-ci (self-healing tips)
        run: npx nx fix-ci
        if: always()

  # Run OSV-Scanner for dependency vulnerabilities
  scan-pr:
    permissions:
      actions: read
      contents: read
      security-events: write
    uses: 'google/osv-scanner-action/.github/workflows/osv-scanner-reusable-pr.yml@v2.2.2'
    with:
      scan-args: |-
        -r
        --skip-git
        ./

    # Security checks
  security:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Secret scanning with Gitleaks
      - name: Secret scan (gitleaks)
        uses: gitleaks/gitleaks-action@v2

      # Run CodeQL for static analysis
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: javascript-typescript

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3

      # Run OpenSSF Scorecards for repo security hygiene
      - name: OpenSSF Scorecards
        uses: ossf/scorecard-action@05b42c624433fc40578a4040d5cf5e36ddca8cde
        with:
          results_file: results.sarif
          results_format: sarif
          publish_results: false # Do not publish results during PRs
          repo_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Scorecards SARIF
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif
